// GENERATED by scripts/gen-tenant-models.mjs — do not edit by hand.
// Run `node scripts/gen-tenant-models.mjs` after changing the Prisma schema.

/**
 * Models the tenant extension filters by `orgId`.
 *
 * Derived from the schema so a new tenant-owned table cannot be added
 * without isolation: the model gets the column, this list follows, and
 * `scoped-models.test.ts` fails if it does not.
 */
export const TENANT_SCOPED_MODELS = new Set<string>([
  "apiKey",
  "auditLog",
  "branch",
  "branchHoliday",
  "bulkUploadBatch",
  "bulkUploadRow",
  "chargeRule",
  "chargeType",
  "city",
  "codCollection",
  "codDeposit",
  "codRemittance",
  "complaint",
  "complaintMessage",
  "creditNote",
  "customer",
  "customerAddress",
  "customerContact",
  "customerUser",
  "deliveryAttempt",
  "deliveryRun",
  "deliveryTask",
  "driver",
  "driverDocument",
  "driverSettlement",
  "escalationRule",
  "etaSnapshot",
  "ewayBillRecord",
  "exception",
  "exceptionAction",
  "fileAsset",
  "freightCalculation",
  "fuelSurchargeRule",
  "geofence",
  "geofenceEvent",
  "gpsPing",
  "inboundReceipt",
  "inboundReceiptLine",
  "invoice",
  "invoiceLine",
  "loadingSheet",
  "loadingSheetLine",
  "loginActivity",
  "maintenanceRecord",
  "manifest",
  "manifestLine",
  "notificationLog",
  "notificationPreference",
  "notificationTemplate",
  "numberSeries",
  "otpToken",
  "outboxEvent",
  "packageLocation",
  "packageType",
  "payment",
  "paymentAllocation",
  "pickupAssignment",
  "pickupAttempt",
  "pickupRequest",
  "pincode",
  "pod",
  "podAsset",
  "rateCard",
  "rateCardVersion",
  "rateSlab",
  "reasonCode",
  "receiptDiscrepancy",
  "reportRun",
  "role",
  "rolePermission",
  "route",
  "routeLeg",
  "savedReport",
  "scanRecord",
  "serviceType",
  "shipment",
  "shipmentCharge",
  "shipmentEvent",
  "shipmentPackage",
  "shipmentSla",
  "slaPolicy",
  "sortBin",
  "state",
  "taxRate",
  "tenantCredential",
  "trackingAlert",
  "trackingProviderConfig",
  "trip",
  "tripEvent",
  "tripExpense",
  "user",
  "userBranchScope",
  "userRole",
  "vehicle",
  "vehicleDocument",
  "vehicleLocation",
  "vehicleStatusLog",
  "vehicleType",
  "vendor",
  "vendorBankAccount",
  "vendorBill",
  "vendorBillLine",
  "vendorPayment",
  "vendorRateContract",
  "vendorRateLine",
  "verificationToken",
  "webhookDelivery",
  "webhookSubscription",
  "zone",
  "zonePincode",
]);

/**
 * Tenant-owned models whose `orgId` is nullable — a shared platform row and
 * a tenant override live in the same table. Filtered as
 * `OR [{ orgId }, { orgId: null }]` on read, and always written with the
 * tenant's own id.
 */
export const TENANT_OPTIONAL_MODELS = new Set<string>([
  "systemConfig",
]);

/**
 * Carry `orgId` but belong to the platform operator, not to a tenant. Never
 * filtered — the operator console reads them across every tenant.
 */
export const OPERATOR_OWNED_MODELS = new Set<string>([
  "impersonationGrant",
  "tenantOnboardingTask",
  "tenantUsageSnapshot",
]);

/**
 * Everything else: child rows isolated through a foreign key to a scoped
 * parent, plus the genuinely global tables (Permission, Organization, the
 * platform-operator identity tables).
 */
export const UNSCOPED_MODELS = new Set<string>([
  "jobRun",
  "organization",
  "permission",
  "platformAdmin",
  "platformAuditLog",
  "session",
  "tenantPlan",
]);
