import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/auth/session";
import { anyBranchScope } from "@/server/repositories/scope";
import { DocumentLogo } from "@/components/documents/letterhead";
import {
  documentDateTime,
  documentMoney,
} from "@/components/documents/format";
import { PrintButton } from "./print-button";

export const metadata: Metadata = { title: "Proof of delivery" };
export const dynamic = "force-dynamic";

/**
 * Proof of delivery, laid out for A4.
 *
 * This is the document a customer downloads from the portal and an accounts
 * department staples to an invoice, so it has to stand on its own: who
 * received it, their relationship to the consignee, when, where, what was
 * collected, and every visit it took to get there.
 *
 * The branded PDF is generated by a worker from this same data once the
 * assets have synced; this page is what it is generated from and what
 * operations prints today.
 */
export default async function PodPage({
  params,
}: {
  params: Promise<{ shipmentId: string }>;
}) {
  const user = await requirePermission("pod.read");
  const { shipmentId } = await params;

  const pod = await prisma.pod.findUnique({
    where: { shipmentId },
    select: {
      id: true,
      receiverName: true,
      receiverRelation: true,
      receiverPhone: true,
      signatureAssetId: true,
      photoAssetId: true,
      otpReference: true,
      latitude: true,
      longitude: true,
      deliveredAt: true,
      recordedAt: true,
      remarks: true,
      agentId: true,
      assets: { select: { id: true, kind: true, fileAssetId: true } },
      task: { select: { attemptNumber: true, run: { select: { number: true } } } },
      shipment: {
        select: {
          id: true,
          orgId: true,
          lrNumber: true,
          mode: true,
          bookedAt: true,
          packageCount: true,
          actualWeight: true,
          chargeableWeight: true,
          goodsDescription: true,
          declaredValue: true,
          paymentType: true,
          codAmount: true,
          originBranchId: true,
          currentBranchId: true,
          destinationBranchId: true,
          consignorName: true,
          consignorCompany: true,
          consignorPhone: true,
          consignorAddress: true,
          consignorPincode: true,
          consigneeName: true,
          consigneeCompany: true,
          consigneePhone: true,
          consigneeAddress: true,
          consigneeLandmark: true,
          consigneePincode: true,
          consignorCity: { select: { name: true } },
          consigneeCity: { select: { name: true } },
          serviceType: { select: { code: true, name: true } },
          originBranch: { select: { code: true, name: true } },
          destinationBranch: {
            select: { code: true, name: true, address: true, phone: true, gstin: true },
          },
          deliveryAttempts: {
            orderBy: { attemptedAt: "asc" },
            select: {
              id: true,
              attemptNumber: true,
              outcome: true,
              attemptedAt: true,
              remarks: true,
              receiverName: true,
              otpVerified: true,
            },
          },
          codCollection: {
            select: {
              amountExpected: true,
              amountCollected: true,
              mode: true,
              reference: true,
              collectedAt: true,
              state: true,
            },
          },
        },
      },
    },
  });

  if (!pod) notFound();

  // Branch scoping applied after the read: a POD is visible to the origin,
  // the destination and wherever the goods currently sit.
  const scoped = await prisma.shipment.findFirst({
    where: {
      id: pod.shipment.id,
      ...anyBranchScope(user, [
        "originBranchId",
        "currentBranchId",
        "destinationBranchId",
      ]),
    },
    select: { id: true },
  });

  if (!scoped) notFound();

  // A POD is stapled to an invoice and read by people outside the company,
  // so the letterhead has to be the carrier that actually moved the goods —
  // hence the lookup by the shipment's own org. `Organization` is global and
  // the tenant extension does not filter it (ADR 001 §4), so a `where`-less
  // read would brand the proof with whichever tenant came back first.
  const [org, agent] = await Promise.all([
    prisma.organization.findUniqueOrThrow({
      where: { id: pod.shipment.orgId },
      select: {
        name: true,
        legalName: true,
        gstin: true,
        phone: true,
        email: true,
        logoUrl: true,
        documentFooter: true,
        supportEmail: true,
        supportPhone: true,
        currency: true,
        timezone: true,
      },
    }),
    pod.agentId
      ? prisma.user.findUnique({
          where: { id: pod.agentId },
          select: { name: true, employeeCode: true },
        })
      : Promise.resolve(null),
  ]);

  const { shipment } = pod;
  const assetHref = (assetId: string) =>
    `/delivery/pod/${shipment.id}/asset/${assetId}`;

  // The desk a consignee is meant to ring about this delivery, and nothing
  // when the carrier has published neither a support line nor a switchboard.
  const support = [
    org.supportPhone ?? org.phone,
    org.supportEmail ?? org.email,
  ]
    .filter(Boolean)
    .join(" · ");

  const facts: Array<[string, string]> = [
    ["Consignment note", shipment.lrNumber],
    ["Service", `${shipment.serviceType.code} · ${shipment.mode}`],
    ["Booked", documentDateTime(shipment.bookedAt, org.timezone)],
    ["Lane", `${shipment.originBranch.code} → ${shipment.destinationBranch.code}`],
    ["Packages", String(shipment.packageCount)],
    ["Weight", `${Number(shipment.chargeableWeight)} kg chargeable`],
    ["Goods", shipment.goodsDescription],
    [
      "Declared value",
      shipment.declaredValue
        ? documentMoney(shipment.declaredValue, org.currency)
        : "—",
    ],
  ];

  return (
    <>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          aside, header { display: none !important; }
          .print-sheet { border: none !important; box-shadow: none !important; padding: 0 !important; }
          .avoid-break { break-inside: avoid; page-break-inside: avoid; }
          @page { size: A4; margin: 12mm; }
        }
      `}</style>

      <div className="no-print mb-6 flex flex-wrap items-center justify-between gap-3">
        <div>
          <p className="font-mono text-[0.65rem] uppercase tracking-[0.15em] text-primary">
            Proof of delivery
          </p>
          <h1 className="text-xl font-semibold tracking-tight">
            {shipment.lrNumber}
          </h1>
        </div>
        <PrintButton />
      </div>

      <article className="print-sheet mx-auto max-w-3xl rounded-lg border bg-card p-8 text-[13px] leading-relaxed">
        {/* Masthead */}
        <header className="flex items-start justify-between gap-6 border-b-2 border-foreground pb-4">
          <div>
            <DocumentLogo src={org.logoUrl} name={org.name} />
            <p className="text-lg font-bold tracking-tight">{org.name}</p>
            {org.legalName && (
              <p className="text-xs text-muted-foreground">{org.legalName}</p>
            )}
            <p className="mt-1 text-xs text-muted-foreground">
              {shipment.destinationBranch.name} ·{" "}
              {shipment.destinationBranch.address}
            </p>
            {shipment.destinationBranch.phone && (
              <p className="text-xs text-muted-foreground">
                {shipment.destinationBranch.phone}
              </p>
            )}
            {(shipment.destinationBranch.gstin ?? org.gstin) && (
              <p className="font-mono text-xs text-muted-foreground">
                GSTIN {shipment.destinationBranch.gstin ?? org.gstin}
              </p>
            )}
          </div>

          <div className="text-right">
            <p className="font-mono text-[0.6rem] uppercase tracking-[0.15em] text-muted-foreground">
              Proof of delivery
            </p>
            <p className="font-mono text-xl font-bold tracking-tight">
              {shipment.lrNumber}
            </p>
            <p className="mt-1 text-xs text-muted-foreground">
              Delivered {documentDateTime(pod.deliveredAt, org.timezone)}
            </p>
            {pod.task?.run?.number && (
              <p className="font-mono text-[0.65rem] text-muted-foreground">
                Run {pod.task.run.number}
              </p>
            )}
          </div>
        </header>

        {/* Receipt — the part that matters */}
        <section className="avoid-break mt-5 rounded-md border-2 border-foreground/80 p-4">
          <p className="font-mono text-[0.6rem] uppercase tracking-[0.15em] text-muted-foreground">
            Received by
          </p>
          <p className="text-lg font-semibold">{pod.receiverName}</p>
          <div className="mt-1 flex flex-wrap gap-x-6 gap-y-1 text-xs text-muted-foreground">
            {pod.receiverRelation && (
              <span>Relationship to consignee: {pod.receiverRelation}</span>
            )}
            {pod.receiverPhone && <span className="font-mono">{pod.receiverPhone}</span>}
            <span>
              Attempt {pod.task?.attemptNumber ?? 1} of{" "}
              {shipment.deliveryAttempts.length}
            </span>
          </div>

          <div className="mt-3 grid gap-3 sm:grid-cols-2">
            <div>
              <p className="font-mono text-[0.55rem] uppercase tracking-[0.15em] text-muted-foreground">
                Signature
              </p>
              {pod.signatureAssetId ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={assetHref(pod.signatureAssetId)}
                  alt="Receiver signature"
                  className="mt-1 h-24 w-full rounded border bg-white object-contain"
                />
              ) : (
                <p className="mt-1 flex h-24 items-center justify-center rounded border border-dashed text-xs text-muted-foreground">
                  Not captured
                </p>
              )}
            </div>

            <div>
              <p className="font-mono text-[0.55rem] uppercase tracking-[0.15em] text-muted-foreground">
                Delivery photograph
              </p>
              {pod.photoAssetId ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={assetHref(pod.photoAssetId)}
                  alt="Delivery photograph"
                  className="mt-1 h-24 w-full rounded border object-cover"
                />
              ) : (
                <p className="mt-1 flex h-24 items-center justify-center rounded border border-dashed text-xs text-muted-foreground">
                  Not captured
                </p>
              )}
            </div>
          </div>

          <dl className="mt-3 grid gap-x-6 gap-y-1 text-xs sm:grid-cols-2">
            <Row
              label="Delivered at"
              value={documentDateTime(pod.deliveredAt, org.timezone)}
            />
            <Row
              label="Recorded at"
              value={documentDateTime(pod.recordedAt, org.timezone)}
            />
            <Row label="Agent" value={agent?.name ?? "—"} />
            <Row
              label="GPS"
              value={
                pod.latitude != null && pod.longitude != null
                  ? `${Number(pod.latitude).toFixed(5)}, ${Number(pod.longitude).toFixed(5)}`
                  : "Not available"
              }
            />
            <Row label="OTP reference" value={pod.otpReference ?? "Not used"} />
            {pod.remarks && <Row label="Remarks" value={pod.remarks} />}
          </dl>
        </section>

        {/* Parties */}
        <section className="avoid-break mt-5 grid gap-4 sm:grid-cols-2">
          <div>
            <p className="font-mono text-[0.55rem] uppercase tracking-[0.15em] text-muted-foreground">
              Consignor
            </p>
            <p className="font-medium">{shipment.consignorName}</p>
            {shipment.consignorCompany && (
              <p className="text-xs text-muted-foreground">
                {shipment.consignorCompany}
              </p>
            )}
            <p className="text-xs text-muted-foreground">
              {shipment.consignorAddress}, {shipment.consignorCity.name}{" "}
              <span className="font-mono">{shipment.consignorPincode}</span>
            </p>
            <p className="font-mono text-xs">{shipment.consignorPhone}</p>
          </div>

          <div>
            <p className="font-mono text-[0.55rem] uppercase tracking-[0.15em] text-muted-foreground">
              Consignee
            </p>
            <p className="font-medium">{shipment.consigneeName}</p>
            {shipment.consigneeCompany && (
              <p className="text-xs text-muted-foreground">
                {shipment.consigneeCompany}
              </p>
            )}
            <p className="text-xs text-muted-foreground">
              {shipment.consigneeAddress}
              {shipment.consigneeLandmark ? `, near ${shipment.consigneeLandmark}` : ""},{" "}
              {shipment.consigneeCity.name}{" "}
              <span className="font-mono">{shipment.consigneePincode}</span>
            </p>
            <p className="font-mono text-xs">{shipment.consigneePhone}</p>
          </div>
        </section>

        {/* Consignment */}
        <section className="avoid-break mt-5">
          <p className="mb-2 font-mono text-[0.55rem] uppercase tracking-[0.15em] text-muted-foreground">
            Consignment
          </p>
          <dl className="grid gap-x-6 gap-y-1 text-xs sm:grid-cols-2">
            {facts.map(([label, value]) => (
              <Row key={label} label={label} value={value} />
            ))}
          </dl>
        </section>

        {/* COD */}
        {shipment.codCollection && (
          <section className="avoid-break mt-5 rounded-md border p-3">
            <p className="mb-2 font-mono text-[0.55rem] uppercase tracking-[0.15em] text-muted-foreground">
              Cash on delivery
            </p>
            <dl className="grid gap-x-6 gap-y-1 text-xs sm:grid-cols-2">
              <Row
                label="Due"
                value={documentMoney(
                  shipment.codCollection.amountExpected,
                  org.currency,
                )}
              />
              <Row
                label="Collected"
                value={documentMoney(
                  shipment.codCollection.amountCollected,
                  org.currency,
                )}
              />
              <Row label="Mode" value={shipment.codCollection.mode.replace("_", " ")} />
              <Row label="Reference" value={shipment.codCollection.reference ?? "—"} />
              <Row
                label="Collected at"
                value={documentDateTime(
                  shipment.codCollection.collectedAt,
                  org.timezone,
                )}
              />
              <Row label="State" value={shipment.codCollection.state} />
            </dl>
          </section>
        )}

        {/* Attempt history */}
        <section className="avoid-break mt-5">
          <p className="mb-2 font-mono text-[0.55rem] uppercase tracking-[0.15em] text-muted-foreground">
            Delivery attempts — {shipment.deliveryAttempts.length}
          </p>
          <table className="w-full border-collapse text-xs">
            <thead>
              <tr className="border-b border-foreground/30 text-left">
                <th className="py-1 pr-2 font-medium">#</th>
                <th className="py-1 pr-2 font-medium">When</th>
                <th className="py-1 pr-2 font-medium">Outcome</th>
                <th className="py-1 font-medium">Notes</th>
              </tr>
            </thead>
            <tbody>
              {shipment.deliveryAttempts.map((attempt) => (
                <tr key={attempt.id} className="border-b border-border/60">
                  <td className="py-1 pr-2 tabular">{attempt.attemptNumber}</td>
                  <td className="py-1 pr-2 tabular">
                    {documentDateTime(attempt.attemptedAt, org.timezone)}
                  </td>
                  <td className="py-1 pr-2">
                    {attempt.outcome === "COLLECTED" ? "Delivered" : "Not delivered"}
                    {attempt.otpVerified ? " · OTP verified" : ""}
                  </td>
                  <td className="py-1 text-muted-foreground">
                    {attempt.receiverName ?? attempt.remarks ?? "—"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="mt-2 text-[0.65rem] text-muted-foreground">
            Every visit made to this address is listed, including any that did
            not result in a handover. This record is append-only.
          </p>
        </section>

        {/*
          The carrier's own footer first — jurisdiction, liability, whatever
          they print on their paperwork — and the provenance line after it.
          The generation stamp is not tenant copy and stays: an accounts
          department stapling this to an invoice needs to know when it was
          taken off the system.
        */}
        <footer className="mt-6 flex flex-col gap-1 border-t pt-3 text-[0.65rem] leading-snug text-muted-foreground">
          {org.documentFooter && <p>{org.documentFooter}</p>}
          <p>
            Generated {documentDateTime(new Date(), org.timezone)} · {org.name}
            {support ? ` · ${support}` : ""}
          </p>
        </footer>
      </article>
    </>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-3 border-b border-border/50 py-0.5">
      <dt className="text-muted-foreground">{label}</dt>
      <dd className="text-right font-medium">{value}</dd>
    </div>
  );
}
