import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronLeft, ShieldCheck } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireCustomerUser } from "@/lib/auth/customer-session";
import { getPortalPod } from "@/lib/portal/queries";
import { PrintButton } from "@/components/portal/print-button";
import { DocumentLogo } from "@/components/documents/letterhead";
import { documentDateTime } from "@/components/documents/format";

export const metadata: Metadata = {
  title: "Proof of delivery",
  robots: { index: false, follow: false },
};

export const dynamic = "force-dynamic";

/**
 * The customer's copy of the proof of delivery.
 *
 * Operations has a fuller version at `/delivery/pod/[shipmentId]` carrying
 * the agent, the run, the capture coordinates and every attempt it took;
 * that view is behind `pod.read` and stays there. This one answers the
 * question a customer actually asks — who signed for my goods, and when —
 * and is laid out to print onto an A4 sheet that can be stapled to an
 * invoice.
 *
 * The branded PDF is generated by a worker once the device assets have
 * synced; this page is what it is generated from.
 */
export default async function PortalPodPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await requireCustomerUser();
  const { id } = await params;

  const pod = await getPortalPod(session, id);
  if (!pod) notFound();

  // This sheet used to say "City Logistics" in the corner, which is our
  // name on a customer's record of their own delivery. The letterhead is
  // read from `session.orgId` rather than from the POD: `getPortalPod`
  // deliberately projects only what a customer may see and does not return
  // an `orgId`, and nothing under `src/app/(portal)` queries
  // `prisma.shipment` directly — that rule is what makes the account
  // scoping provable in one place. The two cannot disagree in any case:
  // both the session and the POD are resolved through the tenant-isolated
  // client against the same host, so the account's org *is* the carrier
  // that moved the goods.
  //
  // `Organization` itself is one of the two global tables the extension
  // does not filter (ADR 001 §4), so the `where` is what keeps another
  // carrier's GSTIN off this page.
  const org = await prisma.organization.findUniqueOrThrow({
    where: { id: session.orgId },
    select: {
      name: true,
      legalName: true,
      gstin: true,
      logoUrl: true,
      address: true,
      city: true,
      state: true,
      pincode: true,
      documentFooter: true,
      supportEmail: true,
      supportPhone: true,
      phone: true,
      email: true,
      timezone: true,
    },
  });

  const orgAddress = [
    org.address,
    [org.city, org.pincode].filter(Boolean).join(" ") || null,
    org.state,
  ].filter((line): line is string => Boolean(line));

  const support = [
    org.supportPhone ?? org.phone,
    org.supportEmail ?? org.email,
  ]
    .filter(Boolean)
    .join(" · ");

  return (
    <div className="mx-auto flex w-full max-w-2xl flex-col gap-6">
      <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
        <Link
          href={`/portal/shipments/${id}`}
          className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
        >
          <ChevronLeft className="size-4" />
          Back to the shipment
        </Link>
        <PrintButton />
      </div>

      <article className="flex flex-col gap-6 rounded-lg border bg-card p-6 print:border-0 print:p-0">
        <header className="flex flex-wrap items-start justify-between gap-4 border-b pb-4">
          <div className="flex flex-col gap-1">
            <p className="font-mono text-[0.6rem] uppercase tracking-[0.16em] text-muted-foreground">
              Proof of delivery
            </p>
            <h1 className="font-mono text-2xl font-semibold tracking-tight">
              {pod.lrNumber}
            </h1>
          </div>
          {/*
            The carrier's letterhead, not ours. This is a record of delivery
            a customer keeps and forwards, so the name on it has to be the
            company that actually moved the goods.
          */}
          <div className="flex flex-col items-end text-right">
            <DocumentLogo src={org.logoUrl} name={org.name} />
            <p className="font-semibold tracking-tight">{org.name}</p>
            {org.legalName && org.legalName !== org.name && (
              <p className="text-xs text-muted-foreground">{org.legalName}</p>
            )}
            {orgAddress.map((line) => (
              <p key={line} className="text-xs text-muted-foreground">
                {line}
              </p>
            ))}
            {org.gstin && (
              <p className="font-mono text-[0.65rem] text-muted-foreground">
                GSTIN {org.gstin}
              </p>
            )}
          </div>
        </header>

        <section className="flex flex-col gap-1">
          <p className="font-mono text-[0.6rem] uppercase tracking-[0.14em] text-muted-foreground">
            Delivered to
          </p>
          <p className="font-medium">{pod.consigneeName}</p>
          <p className="text-sm text-muted-foreground">{pod.consigneeAddress}</p>
          <p className="text-sm text-muted-foreground">
            {pod.toCity} <span className="font-mono">{pod.consigneePincode}</span>
          </p>
        </section>

        <dl className="grid gap-x-8 gap-y-3 border-y py-4 text-sm sm:grid-cols-2">
          <Row
            label="Account"
            value={`${session.customerName} · ${session.customerCode}`}
          />
          <Row label="Received by" value={pod.receiverName} />
          <Row
            label="Relationship"
            value={pod.receiverRelation ?? "Not recorded"}
          />
          <Row
            label="Delivered at"
            value={documentDateTime(pod.deliveredAt, org.timezone)}
          />
          <Row label="Packages" value={String(pod.packageCount)} />
          <Row label="Chargeable weight" value={`${pod.chargeableWeight} kg`} />
          <Row label="Goods" value={pod.goodsDescription} />
        </dl>

        {pod.otpVerified && (
          <p className="inline-flex items-center gap-2 text-sm text-ok">
            <ShieldCheck className="size-4 shrink-0" aria-hidden />
            The recipient confirmed delivery with a one-time code.
          </p>
        )}

        <p className="text-xs text-muted-foreground">
          {pod.documentAssetId
            ? "A signed copy has been generated and will be attached to your invoice."
            : "The signed copy is still being prepared. Print this page in the meantime — it carries the same record."}
        </p>

        {/* The carrier's own closing wording, where they have supplied one. */}
        {(org.documentFooter || support) && (
          <footer className="border-t pt-3 text-xs text-muted-foreground">
            {org.documentFooter && <p>{org.documentFooter}</p>}
            {support && <p className="font-mono text-[0.65rem]">{support}</p>}
          </footer>
        )}
      </article>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col gap-0.5">
      <dt className="font-mono text-[0.6rem] uppercase tracking-[0.13em] text-muted-foreground">
        {label}
      </dt>
      <dd className="font-medium">{value}</dd>
    </div>
  );
}
