import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { format } from "date-fns";
import { ChevronLeft, ShieldCheck } from "lucide-react";
import { requireCustomerUser } from "@/lib/auth/customer-session";
import { getPortalPod } from "@/lib/portal/queries";
import { PrintButton } from "@/components/portal/print-button";

export const metadata: Metadata = {
  title: "Proof of delivery",
  robots: { index: false, follow: false },
};

export const dynamic = "force-dynamic";

/**
 * The customer's copy of the proof of delivery.
 *
 * Operations has a fuller version at `/delivery/pod/[shipmentId]` carrying
 * the agent, the run, the capture coordinates and every attempt it took;
 * that view is behind `pod.read` and stays there. This one answers the
 * question a customer actually asks — who signed for my goods, and when —
 * and is laid out to print onto an A4 sheet that can be stapled to an
 * invoice.
 *
 * The branded PDF is generated by a worker once the device assets have
 * synced; this page is what it is generated from.
 */
export default async function PortalPodPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await requireCustomerUser();
  const { id } = await params;

  const pod = await getPortalPod(session, id);
  if (!pod) notFound();

  return (
    <div className="mx-auto flex w-full max-w-2xl flex-col gap-6">
      <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
        <Link
          href={`/portal/shipments/${id}`}
          className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
        >
          <ChevronLeft className="size-4" />
          Back to the shipment
        </Link>
        <PrintButton />
      </div>

      <article className="flex flex-col gap-6 rounded-lg border bg-card p-6 print:border-0 print:p-0">
        <header className="flex flex-wrap items-start justify-between gap-4 border-b pb-4">
          <div className="flex flex-col gap-1">
            <p className="font-mono text-[0.6rem] uppercase tracking-[0.16em] text-muted-foreground">
              Proof of delivery
            </p>
            <h1 className="font-mono text-2xl font-semibold tracking-tight">
              {pod.lrNumber}
            </h1>
          </div>
          <div className="text-right">
            <p className="font-mono text-[0.6rem] uppercase tracking-[0.14em] text-muted-foreground">
              City Logistics
            </p>
            <p className="text-sm">{session.customerName}</p>
            <p className="font-mono text-xs text-muted-foreground">
              {session.customerCode}
            </p>
          </div>
        </header>

        <section className="flex flex-col gap-1">
          <p className="font-mono text-[0.6rem] uppercase tracking-[0.14em] text-muted-foreground">
            Delivered to
          </p>
          <p className="font-medium">{pod.consigneeName}</p>
          <p className="text-sm text-muted-foreground">{pod.consigneeAddress}</p>
          <p className="text-sm text-muted-foreground">
            {pod.toCity} <span className="font-mono">{pod.consigneePincode}</span>
          </p>
        </section>

        <dl className="grid gap-x-8 gap-y-3 border-y py-4 text-sm sm:grid-cols-2">
          <Row label="Received by" value={pod.receiverName} />
          <Row
            label="Relationship"
            value={pod.receiverRelation ?? "Not recorded"}
          />
          <Row
            label="Delivered at"
            value={format(pod.deliveredAt, "dd MMM yyyy · HH:mm")}
          />
          <Row label="Packages" value={String(pod.packageCount)} />
          <Row label="Chargeable weight" value={`${pod.chargeableWeight} kg`} />
          <Row label="Goods" value={pod.goodsDescription} />
        </dl>

        {pod.otpVerified && (
          <p className="inline-flex items-center gap-2 text-sm text-ok">
            <ShieldCheck className="size-4 shrink-0" aria-hidden />
            The recipient confirmed delivery with a one-time code.
          </p>
        )}

        <p className="text-xs text-muted-foreground">
          {pod.documentAssetId
            ? "A signed PDF copy has been generated and will be attached to your invoice."
            : "The signed PDF copy is still being prepared. Print this page in the meantime — it carries the same record."}
        </p>
      </article>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col gap-0.5">
      <dt className="font-mono text-[0.6rem] uppercase tracking-[0.13em] text-muted-foreground">
        {label}
      </dt>
      <dd className="font-medium">{value}</dd>
    </div>
  );
}
